spring.application.name=phonenumberApi
# استخدم مسار ملف محلي بدلاً من mem
spring.datasource.url=jdbc:h2:file:./data/phonenumberdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# البورت الثابت
server.port=8000